# Generated by Django 6.0 on 2026-01-08 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_department_exam_department_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.department'),
        ),
    ]
