# Generated by Django 6.0 on 2026-01-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_exam_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='exams', to='exams.department'),
        ),
    ]
